name: Deploy Object Detection App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI server
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &

    - name: Create images_predicted directory
      run: mkdir -p ../images_predicted

    - name: Upload All Images for Prediction
      uses: ./.github/actions/upload-images
      with:
        api_url: "http://localhost:8000/predict"

    - name: Archive predicted images
      run: |
        zip -r predicted_images.zip ../images_predicted
      continue-on-error: true

    - name: Upload predicted images artifact
      uses: actions/upload-artifact@v2
      with:
        name: predicted-images
        path: predicted_images.zip